[project]
site_name = "pygame-topdownengine Documentation"
site_url = "https://shaurya-sharma-dev.github.io/pygame-topdownengine/"
repo_url = "https://github.com/shaurya-sharma-dev/pygame-topdownengine/" 
repo_name = "pygame-topdownengine"

nav = [
  { "Home" = "index.md" },
  { "Getting Started" = [
    { "Installation" = "installation.md" },
    { "Making Your First Game" = [
      { "Part 1: Quickstart" = "tutorial\\1_quickstart" },
      { "Part 2: Lighting" = "tutorial\\2_lighting" }
    ]}
  ]},
  { "API Reference" = [
    { "topdownengine.asset_paths" = "api\\asset_paths" },
    { "topdownengine.camera" = "api\\camera" },
    { "topdownengine.controls" = "api\\controls" },
    { "topdownengine.env_object" = "api\\env_object" },
    { "topdownengine.font" = "api\\font" },
    { "topdownengine.game_object" = "api\\game_object" },
    { "topdownengine.game" = "api\\game" },
    { "topdownengine.math" = "api\\math" },
    { "topdownengine.mobile_object" = "api\\mobile_object" },
    { "topdownengine.scenes" = "api\\scenes" },
    { "topdownengine.ui" = "api\\ui" },
    { "topdownengine.visual_utils" = "api\\visual_utils" }
  ]}
]

[project.extra.version]
provider = "mike"   # Uses mike
alias = true        # Shows aliases (like 'latest') next to the number
default = "latest"  # The version to fall back on

[theme]
variant = "modern"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"                        # Standard light theme variant
toggle.icon = "lucide/moon"               # The button looks like a moon
toggle.name = "Switch to dark mode"        # Accessibility tooltip text

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"                          # Zensical's default dark variant
toggle.icon = "lucide/sun"                # The button looks like a sun
toggle.name = "Switch to light mode"       # Accessibility tooltip text

[features]
navigation_tabs = true
navigation_sections = true
navigation_instant = true

[[plugins]]
name = "search"

[[plugins]]
name = "autorefs"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["topdownengine"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = true