[project]
site_name = "pygame-topdownengine Documentation"
site_url = "https://shaurya-sharma-dev.github.io/pygame-topdownengine/"
repo_url = "https://github.com/shaurya-sharma-dev/pygame-topdownengine/" 
repo_name = "pygame-topdownengine"

nav = [
  { "Home" = "index.md" },
  { "Installation" = "installation.md" },
  { "Quickstart" = "quickstart.md" },
  { "API Reference" = [
    { "topdownengine.asset_paths" = "api\\asset_paths.md" },
    { "topdownengine.camera" = "api\\camera.md" },
    { "topdownengine.controls" = "api\\controls.md" },
    { "topdownengine.env_object" = "api\\env_object.md" },
    { "topdownengine.font" = "api\\font.md" },
    { "topdownengine.game_object" = "api\\game_object.md" },
    { "topdownengine.game" = "api\\game.md" },
    { "topdownengine.math" = "api\\math.md" },
    { "topdownengine.mobile_object" = "api\\mobile_object.md" },
    { "topdownengine.scenes" = "api\\scenes.md" },
    { "topdownengine.ui" = "api\\ui.md" },
    { "topdownengine.visual_utils" = "api\\visual_utils.md" }
  ]}
]

[theme]
variant = "modern"

[features]
navigation_tabs = true
navigation_sections = true
navigation_instant = true

[[plugins]]
name = "search"

[[plugins]]
name = "autorefs"

[[plugins]]
name = "mkdocstrings"

[plugins.config.handlers.python]
paths = ["topdownengine"]
options = { docstring_style = "google", show_source = true }