title: "pygame-topdownengine Documentation"
description: "A documentation for the pygame-topdownengine game engine."

# URL Settings (Crucial for GitHub Pages layout tracking)
url: "https://shaurya-sharma-dev.github.io" 
baseurl: "/pygame-topdownengine"             

# Themes and Plugins
remote_theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap